"""CLI entrypoint for Aegis Agent."""

from __future__ import annotations

import argparse
import sys
from collections.abc import Sequence
from pathlib import Path

from src.agent.tools import (
    apply_patch_preview_tool,
    dumps_report_json,
    get_tool_schemas,
    render_html_report,
    render_markdown_report,
    render_patch_apply_result_markdown,
    render_tool_schemas_markdown,
)
from src.agent.workflow import (
    AgentDependencyError,
    get_workflow_spec,
    render_workflow_markdown,
    render_workflow_mermaid,
    run_agent_workflow,
)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="aegis-agent",
        description="Aegis Agent: LangGraph security diagnosis workflow over the local Aegis scanner.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    tools = subparsers.add_parser("tools", help="Export OpenAI-style Agent tool schemas.")
    tools.add_argument(
        "--format",
        "-f",
        choices=["json", "markdown"],
        default="json",
        help="Tool schema format (default: json).",
    )
    tools.add_argument("--output", "-o", type=str, help="Output path. Defaults to stdout.")

    workflow = subparsers.add_parser("workflow", help="Export the static Agent workflow graph.")
    workflow.add_argument(
        "--format",
        "-f",
        choices=["json", "markdown", "mermaid"],
        default="mermaid",
        help="Workflow format (default: mermaid).",
    )
    workflow.add_argument("--output", "-o", type=str, help="Output path. Defaults to stdout.")

    apply_fix = subparsers.add_parser(
        "apply-fix",
        help="Validate and optionally apply one patch preview from a JSON diagnosis report.",
    )
    apply_fix.add_argument("report_path", type=str, help="JSON report generated by aegis-agent diagnose.")
    apply_fix.add_argument("--finding-id", required=True, help="Finding id to apply from the report.")
    apply_fix.add_argument("--project-path", type=str, help="Project path override; must match report summary.")
    apply_fix.add_argument(
        "--yes",
        action="store_true",
        help="Actually write the validated patch preview. Without this flag, apply-fix is a dry run.",
    )
    apply_fix.add_argument(
        "--rescan",
        action="store_true",
        help="After --yes applies a patch, rescan the project without cache and report whether the target finding remains.",
    )
    apply_fix.add_argument(
        "--format",
        "-f",
        choices=["json", "markdown"],
        default="markdown",
        help="Apply result format (default: markdown).",
    )
    apply_fix.add_argument("--output", "-o", type=str, help="Output path. Defaults to stdout.")

    diagnose = subparsers.add_parser("diagnose", help="Scan a project and generate an Agent diagnosis report.")
    diagnose.add_argument("project_path", type=str, help="Project directory to diagnose.")
    diagnose.add_argument(
        "--format",
        "-f",
        choices=["json", "markdown", "html"],
        default="markdown",
        help="Report format (default: markdown).",
    )
    diagnose.add_argument("--output", "-o", type=str, help="Report output path. Defaults to stdout.")
    diagnose.add_argument("--top-k", type=int, default=3, help="Knowledge snippets per finding (default: 3).")
    diagnose.add_argument("--baseline", type=str, help="Baseline path used as project memory.")
    diagnose.add_argument("--ignore", nargs="+", help="Directories or file patterns to ignore during scanning.")
    diagnose.add_argument("--engine", choices=["new", "legacy"], default="new", help="Scanner engine (default: new).")
    diagnose.add_argument("--no-cache", action="store_true", help="Disable scanner cache.")
    diagnose.add_argument("--no-parallel", action="store_true", help="Disable scanner parallelism.")
    diagnose.add_argument("--max-workers", type=int, help="Maximum scanner workers.")
    diagnose.add_argument(
        "--rules-dir",
        type=str,
        action="append",
        metavar="PATH",
        help="Extra DSL rules directory; may be passed multiple times.",
    )
    ai_group = diagnose.add_mutually_exclusive_group()
    ai_group.add_argument(
        "--ai", dest="use_ai", action="store_true", help="Explicitly call the configured AI provider."
    )
    ai_group.add_argument("--no-ai", dest="use_ai", action="store_false", help="Use offline remediation only.")
    diagnose.set_defaults(use_ai=False)

    return parser


def _write_output(text: str, output: str | None) -> None:
    if output:
        path = Path(output)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        sys.stderr.write(f"Aegis Agent report saved to: {path}\n")
        return
    sys.stdout.write(text)


def run(argv: Sequence[str] | None = None) -> int:
    """Run the CLI and return an exit code."""
    parser = _build_parser()
    args = parser.parse_args(list(argv) if argv is not None else None)

    if args.command == "tools":
        rendered = (
            dumps_report_json({"tools": get_tool_schemas()}) + "\n"
            if args.format == "json"
            else render_tool_schemas_markdown()
        )
        _write_output(rendered, args.output)
        return 0

    if args.command == "workflow":
        if args.format == "json":
            rendered = dumps_report_json(get_workflow_spec()) + "\n"
        elif args.format == "markdown":
            rendered = render_workflow_markdown()
        else:
            rendered = render_workflow_mermaid()
        _write_output(rendered, args.output)
        return 0

    if args.command == "apply-fix":
        result = apply_patch_preview_tool(
            report_path=args.report_path,
            finding_id=args.finding_id,
            project_path=args.project_path,
            confirm=bool(args.yes),
            rescan=bool(args.rescan),
        )
        rendered = (
            dumps_report_json(result) + "\n" if args.format == "json" else render_patch_apply_result_markdown(result)
        )
        _write_output(rendered, args.output)
        return 0 if result.get("status") in {"dry_run", "applied"} else 2

    if args.command != "diagnose":
        parser.error("unknown command")

    project_path = Path(args.project_path).resolve()
    if not project_path.exists() or not project_path.is_dir():
        sys.stderr.write(f"Project path does not exist or is not a directory: {project_path}\n")
        return 2

    try:
        report = run_agent_workflow(
            str(project_path),
            baseline_path=args.baseline,
            top_k=max(1, int(args.top_k)),
            use_ai=bool(args.use_ai),
            ignore_patterns=args.ignore,
            no_cache=bool(args.no_cache),
            no_parallel=bool(args.no_parallel),
            max_workers=args.max_workers,
            engine=args.engine,
            rules_dirs=args.rules_dir,
        )
    except AgentDependencyError as exc:
        sys.stderr.write(f"{exc}\n")
        return 2

    if args.format == "json":
        rendered = dumps_report_json(report) + "\n"
    elif args.format == "html":
        rendered = render_html_report(report)
    else:
        rendered = render_markdown_report(report)
    _write_output(rendered, args.output)
    return 0


def main() -> None:
    """Console script entrypoint."""
    raise SystemExit(run())


if __name__ == "__main__":
    main()
